### ISSUE TITLE
Please add screeners

### ISSUE THREAD

**Issue by cforce** [zauni/redmine_wiki_imagemap#1]
Dunno what this imagemap really is, please shows some examples..!

**Comment by zauni** [comment]
Hi,
wikipedia has a great explanation and an example: http://en.wikipedia.org/wiki/Image_map

In short: this plugin helps you to show images in the redmine wiki, which have links in certain parts of the image. For example you could show an image of a piechart and place links on different parts of the pie.

Hopefully this helps you!
